spring:
  application:
    name: notifications-service

server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mailtrap:
  api:
    token: ${PASSWORD_MAIL}
  sender: 
    email: hello@demomailtrap.com
    name: Notificaciones Administrador de Tareas
