spring:
  application:
    name: tasks-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default: # Configuración base
        slidingWindowSize: 10
        ignoreExceptions:
          - feign.FeignException.NotFound
    instances:
      users-service:
        baseConfig: default # Hereda lo de arriba